repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.31.3
  hooks:
    - id: check-jsonschema
      name: "Check Service JSON against schema definition"
      files: ^(make_a_lpa|use_a_lasting_power_of_attorney_service|complete_the_deputy_report_service)/
      types: [json]
      args: ["--schemafile", "schema.json"]
- repo: https://github.com/renovatebot/pre-commit-hooks
  rev: 39.205.1
  hooks:
    - id: renovate-config-validator
