services:
  builder:
    container_name: node_build
    build:
      context: ./
    volumes:
      - ./src:/app/src
      - ./_site:/app/_site
      - ./.eleventy.js:/app/.eleventy.js
    command: ["npm", "run", "build"]

  server:
    container_name: node_server
    build:
      context: ./
    volumes:
      - ./src:/app/src
      - ./_site:/app/_site
      - ./.eleventy.js:/app/.eleventy.js
    ports:
      - "8089:8080"
    command: ["npm", "run", "start"]

  validator:
    container_name: node_validator
    build:
      context: ./
    volumes:
      - ./src:/app/src
      - ./_site:/app/_site
      - ./.eleventy.js:/app/.eleventy.js
      - ./validate:/app/validate
    ports:
      - "8089:8080"
    command: ["node", "./validate/index.js"]
