name: "[Lighthouse] Run Lighthouse CI"

defaults:
  run:
    shell: bash

on:
  workflow_call:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            http://docs.performance.opg.service.justice.gov.uk/
            http://docs.performance.opg.service.justice.gov.uk/use-a-lasting-power-of-attorney-service/
            http://docs.performance.opg.service.justice.gov.uk/make-a-lasting-power-of-attorney-service/
          budgetPath: ./src/_includes/budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
