name: "[workflow] Pull Request"

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Linux build on node
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Run Build
        run: docker compose up builder

